# Generated by Django 4.1.4 on 2023-03-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0007_alter_post_author'),
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(related_name='aimé_par', to='core_post.post'),
        ),
    ]
