# Generated by Django 4.1.4 on 2023-03-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0007_alter_post_author'),
        ('core_user', '0002_user_posts_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_post.post'),
        ),
    ]
