name: Build, Test and Deploy Postagram
on:
 push:
   branches: [ master ]



build-test : 
 runs-on : ubuntu-latest 
 steps : 
 - uses : actions/checkout@v2 
 - name : Injecting env vars 
   run : |
     echo "
            DATABASE_NAME=apidb
            DATABASE_USER=tester
            DATABASE_PASSWORD=wCh29&HE&T83
            DATABASE_PORT=5432
            ENV=DEV
            DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
            " >> .env


- name: Building containers
 run: |
   docker-compose up 

- name: Running Tests
 run: |
   docker-compose exec -T api pytest
